version: '3.8'

services:
  # Сервис для приложения
  app:
    image: openjdk:17-jdk-slim
    container_name: webrise-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/webrise_db
      - SPRING_DATASOURCE_USERNAME=webrise_user
      - SPRING_DATASOURCE_PASSWORD=webrise_password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13
    container_name: webrise-db
    environment:
      POSTGRES_USER: webrise_user
      POSTGRES_PASSWORD: webrise_password
      POSTGRES_DB: webrise_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: